const persianNameMap = {
  BTCIRT: 'بیت‌کوین',
  ETHIRT: 'اتریوم',
  USDTIRT: 'تتر',
  XRPIRT: 'ریپل',
  ADAIRT: 'کاردانو',
  DOGEIRT: 'دوج‌کوین',
  TRXIRT: 'ترون',
  SOLIRT: 'سولانا',
  DOTIRT: 'پولکادات',
  LTCIRT: 'لایت‌کوین',
  BNBIRT: 'بایننس کوین',
  XLMIRT: 'استلار',
  AVAXIRT: 'آوالانچ',
  UNIIRT: 'یونی سواپ',
  LINKIRT: 'چین لینک',
  XMRIRT: 'مونرو',
  AAVEIRT: 'آوه',

  ADAUSDT: 'کاردانو',
  AVAXUSDT: 'آوالانچ',
  BNBUSDT: 'بایننس کوین',
  BTCUSDT: 'بیت‌کوین',
  DOGEUSDT: 'دوج‌کوین',
  DOTUSDT: 'پولکادات',
  ETHUSDT: 'اتریوم',
  LINKUSDT: 'چین لینک',
  LTCUSDT: 'لایت‌کوین',
  SOLUSDT: 'سولانا',
  TRXUSDT: 'ترون',
  UNIUSDT: 'یونی سواپ',
  USDCUSDT: 'یواس‌دی کوین',
  XRPUSDT: 'ریپل',
  XLMUSDT: 'استلار',
  AAVEUSDT: 'آوه',
  SHIBIRT: 'شیبا اینو',
  ETCIRT: 'اتریوم کلاسیک',
  BCHIRT: 'بیت‌کوین کش',
  EOSIRT: 'ایاس',
  MATICIRT: 'پالیگان',
  FTMIRT: 'فانتوم',
  ATOMIRT: 'کازماس',
  MKRIRT: 'میکر',
  SANDIRT: 'سندباکس',
  MANAIRT: 'دیسنترالند',
  CAKEIRT: 'پنکیک سواپ',
  COMPIRT: 'کامپوند',
  CHZIRT: 'چیلیز',
  ENJIRT: 'انجین کوین',
  CRVIRT: 'کرو دائو',
  '1INCHIRT': 'وان اینچ',
  GRTIRT: 'گراف',
  YFIIRT: 'یرن فایننس',
  SNXIRT: 'سینتتیکس',
  ZRXIRT: 'زیرو ایکس',
  BATIRT: 'بت',
  RENIRT: 'رن',
  UMAIRT: 'یو ام ای',
  SUSHIIRT: 'سوشی سواپ',
  LRCIRT: 'لوپرینگ',
  STMXIRT: 'استورم ایکس',
  ANKRIRT: 'آنکر',
  KNCIRT: 'کایبر نتورک',
  OCEANIRT: 'اوشن پروتکل',
  BANDIRT: 'بند پروتکل',
  TOMOIRT: 'توموچین',
  ICXIRT: 'آیکون',
  SCIRT: 'سیاکوین',
  ZILIRT: 'زیلیکا',
  VETIRT: 'وی چین',
  HOTIRT: 'هولو',
  CELRIRT: 'سلر نتورک',
  CVCIRT: 'سیویک',
  DOCKIRT: 'داک',
  REQIRT: 'ریکوئست',
  FUNIRT: 'فان‌فیر',
  PERLIRT: 'پرل',
  DENTIRT: 'دنت',
  WINIRT: 'وین‌کینک',
  FETIRT: 'فچ‌ای‌آی',
  RSRIRT: 'ریزرور رایت',
  BTTIRT: 'بیت‌تورنت',
  XVSIRT: 'ونوس',
  ALGOIRT: 'آلگوراند',
  FILIRT: 'فایل کوین',
  EGLDIRT: 'الروند',
  GALAIRT: 'گالا',
  AXSIRT: 'اکسی اینفینیتی',
  FLOWIRT: 'فلو',
  ROSEIRT: 'اُیسیس نتورک',
  NEARIRT: 'نیر پروتکل',
  TWTIRT: 'تراست ولت توکن',
  GMTIRT: 'استپن',
  OPIRT: 'آپتیمیسم',
  ARBIRT: 'آربیتروم',
  SUIIRT: 'سویی',
  PEPEIRT: 'پپه',
  FLOKIIRT: 'فلوکی اینو',
  WLDIRT: 'ورلد‌کوین',
  TONIRT: 'تون‌کوین',
  TONUSDT: 'تون‌کوین',
  ZECIRT: 'زدکش',
  XTZIRT: 'تزوس',
  DAIIRT: 'دای',
  POLIRT: 'پولِگان',
  '1K_SHIBIRT': 'شیبا ۱۰۰۰تایی',
  BALIRT: 'بالنسر',
  '1M_BTTIRT': 'بیت تورنت ۱ میلیونی',
  MASKIRT: 'ماسک',
  APEIRT: 'ایپ کوین',
  ONEIRT: 'هارمونی',
  WBTCIRT: 'رپد بیت‌کوین',
  USDCIRT: 'یواس‌دی کوین',
  QNTIRT: 'کوآنت',
  HBARIRT: 'هدرا هش‌گراف',
  EGALAIRT: 'گالا',
  MASKIRT: 'ماسک',
  ENSIRT: 'اتریوم نیم سرویس',
  LDOIRT: 'لیدو دائو',
  DYDXIRT: 'دی‌وای‌دی‌اکس',
  APTIRT: 'اپتوس',
  LPTIRT: 'لایو پیر',
  GLMIRT: 'گولم',
  API3IRT: 'ای‌پی‌آی۳',
  DAOIRT: 'دائو',
  NMRIRT: 'نومرایر',
  STORJIRT: 'استورج',
  CVXIRT: 'کرو فایننس',
  SNTIRT: 'استاتوس',
  SLPIRT: 'اسموث لاو پوشن',
  '1M_NFTIRT': 'ان‌اف‌تی ۱ میلیونی',
  TIRT: 'تتر',
  '1B_BABYDOGEIRT': 'بیبی‌دوج ۱ میلیاردی',
  '100K_FLOKIIRT': 'فلوکی ۱۰۰ هزاری',
  IMXIRT: 'ای‌ام‌ایکس',
  MDTIRT: 'میز دیتا توکن',
  BLURIRT: 'بلور',
  MAGICIRT: 'مجیک',
  PAXGIRT: 'پکس‌گلد',
  GMXIRT: 'جی‌ام‌ایکس',
  SSVIRT: 'اس‌اس‌وی',
  OMGIRT: 'اُمِی‌جی',
  AGLDIRT: 'اِی‌جی‌ال‌دی',
  RDNTIRT: 'رِیدنِت',
  JSTIRT: 'جاست',
  RENDERIRT: 'رندر',
  BICOIRT: 'بیکو',
  WOOIRT: 'وو',
  SKLIRT: 'اسکیل',
  TRBIRT: 'تلور',
  MEMEIRT: 'میم',
  ETHFIIRT: 'اترفای',
  NOTIRT: 'نات',
  '1M_PEPEIRT': 'پپه ۱ میلیونی',
  OMIRT: 'مانترا',
  AEVOIRT: 'ایوو',
  WIRT: 'ورلد',
  ZROIRT: 'زیرو',
  GIRT: 'جی',
  ONDOIRT: 'اوندو',
  DOGSIRT: 'داگز',
  CATIIRT: 'کتی',
  HMSTRIRT: 'همستر',
  XAUTIRT: 'تتر طلا',
  EIGENIRT: 'ایگن',
  JASMYIRT: 'جسمی',
  ENAIRT: 'اِنا',
  PENDLEIRT: 'پندل',
  SUPERIRT: 'سوپر',
  EDUIRT: 'ادو',
  SAFEIRT: 'سیف',
  XIRT: 'اکس',
  BANANAIRT: 'بانانا',
  MAJORIRT: 'میجر',
  MOVEIRT: 'موو',
  STRKIRT: 'استارک‌نت',
  METISIRT: 'متیس',
  INJIRT: 'اینجکتیو',
  TURBOIRT: 'توربو',
  DEXEIRT: 'دکس‌ای',
  ATHIRT: 'آث',
  COOKIEIRT: 'کوکی',
  CGPTIRT: 'کریپتو جی‌پی‌تی',
  SIRT: 'اس',
  NEIROIRT: 'نیرو',
  '1K_BONKIRT': 'بانک ۱۰۰۰تایی',
  MORPHOIRT: 'مورفو',
  '1K_CATIRT': 'کت ۱۰۰۰تایی',
  FORMIRT: 'فرم',
  WIFIRT: 'وایف',
  RAYIRT: 'ری',
  TNSRIRT: 'تنسر',
  AIXBTIRT: 'ای‌آی ایکس بی‌تی',
  VIRTUALIRT: 'ویرچوال',
  KAITOIRT: 'کایتو',
  PENGUIRT: 'پنگوئن',
  JUPIRT: 'ژوپیتر',
  IOIRT: 'آی‌او',
  IOTXIRT: 'آی‌اوتکس',
  ZKJIRT: 'زد‌کا‌جی',
  NEXOIRT: 'نکسو',
  AMPIRT: 'امپلیفای',
  CFXIRT: 'کون‌فلاکس',
  ALTIRT: 'آلت',
  AXLIRT: 'اکسل',
  PUMPIRT: 'پامپ',
  LAYERIRT: 'لِیِر',
  PNUTIRT: 'پی‌نات',
  PMNUSDT: 'پی‌ام‌ان',
  AUSDT: 'تتر آ',
  AIRT: 'ای تتر',
  BCHUSDT: 'بیت‌کوین کش',
  XMRUSDT: 'مونرو',
  ETCUSDT: 'اتریوم کلاسیک',
  ZECUSDT: 'زدکش',
  XTZUSDT: 'تزوس',
  DAIUSDT: 'دای',
  POLUSDT: 'پالیگان',
  FILUSDT: 'فایل کوین',
  GRTUSDT: 'گراف',
  '1K_SHIBUSDT': 'شیبا ۱۰۰۰تایی',
  '1INCHUSDT': 'وان اینچ',
  ANKRUSDT: 'آنکر',
  ATOMUSDT: 'کازماس',
  AXSUSDT: 'اکسی اینفینیتی',
  BALUSDT: 'بالنسر',
  BANDUSDT: 'بند پروتکل',
  BATUSDT: 'بت',
  '1M_BTTUSDT': 'بیت تورنت ۱ میلیونی',
  CELRUSDT: 'سلر نتورک',
  COMPUSDT: 'کامپوند',
  EGLDUSDT: 'الروند',
  MASKUSDT: 'ماسک',
  MKRUSDT: 'میکر',
  NEARUSDT: 'نیر پروتکل',
  SNXUSDT: 'سینتتیکس',
  SUSHIUSDT: 'سوشی سواپ',
  YFIUSDT: 'یرن فایننس',
  ZILUSDT: 'زیلیکا',
  MANAUSDT: 'دیسنترالند',
  SANDUSDT: 'سندباکس',
  APEUSDT: 'ایپ کوین',
  ONEUSDT: 'هارمونی',
  WBTCUSDT: 'رپد بیت‌کوین',
  ALGOUSDT: 'آلگوراند',
  GMTUSDT: 'استپن',
  CHZUSDT: 'چیلیز',
  QNTUSDT: 'کوآنت',
  FLOWUSDT: 'فلو',
  HBARUSDT: 'هدرا هش‌گراف',
  EGALAUSDT: 'گالا',
  ENJUSDT: 'انجین کوین',
  CRVUSDT: 'کرو دائو',
  CAKEUSDT: 'پنکیک سواپ',
  LDOUSDT: 'لیدو دائو',
  DYDXUSDT: 'دی‌وای‌دی‌اکس',
  APTUSDT: 'اپتوس',
  LRCUSDT: 'لوپرینگ',
  ENSUSDT: 'اتریوم نیم سرویس',
  LPTUSDT: 'لایو پیر',
  GLMUSDT: 'گولم',
  API3USDT: 'ای‌پی‌آی۳',
  DAOUSDT: 'دائو',
  CVCUSDT: 'سیویک',
  NMRUSDT: 'نومرایر',
  STORJUSDT: 'استورج',
  CVXUSDT: 'کرو فایننس',
  SNTUSDT: 'استاتوس',
  SLPUSDT: 'اسموث لاو پوشن',
  '1M_NFTUSDT': 'ان‌اف‌تی ۱ میلیونی',
  TUSDT: 'تتر',
  '1B_BABYDOGEUSDT': 'بیبی‌دوج ۱ میلیاردی',
  '100K_FLOKIUSDT': 'فلوکی ۱۰۰ هزاری',
  ZRXUSDT: 'زیرو ایکس',
  IMXUSDT: 'ای‌ام‌ایکس',
  MDTUSDT: 'میز دیتا توکن',
  BLURUSDT: 'بلور',
  MAGICUSDT: 'مجیک',
  ARBUSDT: 'آربیتروم',
  PAXGUSDT: 'پکس‌گلد',
  GMXUSDT: 'جی‌ام‌ایکس',
  SSVUSDT: 'اس‌اس‌وی',
  WLDUSDT: 'ورلد‌کوین',
  OMGUSDT: 'اُمِی‌جی',
  AGLDUSDT: 'اِی‌جی‌ال‌دی',
  RDNTUSDT: 'رِیدنِت',
  JSTUSDT: 'جاست',
  RENDERUSDT: 'رندر',
  BICOUSDT: 'بیکو',
  WOOUSDT: 'وو',
  SKLUSDT: 'اسکیل',
  FETUSDT: 'فچ‌ای‌آی',
  TRBUSDT: 'تلور',
  RSRUSDT: 'ریزرور رایت',
  MEMEUSDT: 'میم',
  UMAUSDT: 'یو ام ای',
  ETHFIUSDT: 'اترفای',
  NOTUSDT: 'نات',
  '1M_PEPEUSDT': 'پپه ۱ میلیونی',
  OMUSDT: 'مانترا',
  AEVOUSDT: 'ایوو',
  WUSDT: 'ورلد',
  ZROUSDT: 'زیرو',
  GUSDT: 'جی',
  ONDOUSDT: 'اوندو',
  DOGSUSDT: 'داگز',
  CATIUSDT: 'کتی',
  HMSTRUSDT: 'همستر',
  XAUTUSDT: 'تتر طلا',
  EIGENUSDT: 'ایگن',
  JASMYUSDT: 'جسمی',
  ENAUSDT: 'اِنا',
  PENDLEUSDT: 'پندل',
  SUPERUSDT: 'سوپر',
  HOTUSDT: 'هولو',
  EDUUSDT: 'ادو',
  SAFEUSDT: 'سیف',
  XUSDT: 'اکس',
  BANANAUSDT: 'بانانا',
  MAJORUSDT: 'میجر',
  MOVEUSDT: 'موو',
  STRKUSDT: 'استارک‌نت',
  METISUSDT: 'متیس',
  INJUSDT: 'اینجکتیو',
  TURBOUSDT: 'توربو',
  DEXEUSDT: 'دکس‌ای',
  ATHUSDT: 'آث',
  COOKIEUSDT: 'کوکی',
  CGPTUSDT: 'کریپتو جی‌پی‌تی',
  SUSDT: 'اس',
  NEIROUSDT: 'نیرو',
  '1K_BONKUSDT': 'بانک ۱۰۰۰تایی',
  MORPHOUSDT: 'مورفو',
  '1K_CATUSDT': 'کت ۱۰۰۰تایی',
  FORMUSDT: 'فرم',
  WIFUSDT: 'وایف',
  RAYUSDT: 'ری',
  TNSRUSDT: 'تنسر',
  AIXBTUSDT: 'ای‌آی ایکس بی‌تی',
  VIRTUALUSDT: 'ویرچوال',
  KAITOUSDT: 'کایتو',
  PENGUUSDT: 'پنگوئن',
  JUPUSDT: 'ژوپیتر',
  IOUSDT: 'آی‌او',
  IOTXUSDT: 'آی‌اوتکس',
  ZKJUSDT: 'زد‌کا‌جی',
  NEXOUSDT: 'نکسو',
  AMPUSDT: 'امپلیفای',
  CFXUSDT: 'کون‌فلاکس',
  ALTUSDT: 'آلت',
  AXLUSDT: 'اکسل',
  PUMPUSDT: 'پامپ',
  LAYERUSDT: 'لِیِر',
  PNUTUSDT: 'پی‌نات',
};

module.exports = persianNameMap;
